# Generated by Django 4.1.2 on 2023-01-28 08:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='rollno',
            field=models.IntegerField(null=True),
        ),
    ]
