# Generated by Django 4.1.2 on 2023-01-28 08:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0002_studentmodel_rollno'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentmodel',
            name='rollno',
        ),
    ]
