# Generated by Django 4.1.5 on 2023-02-03 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Teacher', '0003_remove_studentmodel_rollno'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentmodel',
            name='image',
            field=models.ImageField(null=True, upload_to='student_images'),
        ),
    ]
